pkolaczk/latte

- Cargo.lock
- Cargo.toml
- src/deadline.rs
- src/main.rs
- src/workload.rs
By not sharing Rune stuff we waste a bit of memory,
but we allow each task to run independently.
Rune uses Arc heavily, and they become a bottleneck
on multicore computers.
Running empty benchmark on 24 cores:
before: 1,403,487 calls per second
after: 30,981,323 calls per second
Fixes #9
> Unshare Unit and Context

- src/report.rs
> Set response time percentile precision to 3 decimal places

- src/sampler.rs
Some information about the last snapshot point was
not recorded properly in the Sampler which in some cases
led to `far_from_the_end` variable turn to false too early
and new samples were not emitted anymore.
Fixes #27
> Fix recording of the last snapshot cycle count and time

- src/sampler.rs
Fixes:
thread 'main' panicked at 'attempt to subtract with overflow', src/sampler.rs:43:44
> Fix possible numeric underflow in sampler:43

- src/stats.rs
Running `cargo clippy --all-targets` picks up this extra warning.
> Fix clippy lint

- src/context.rs
- src/workload.rs
The readme mentions a `fs::read_to_string(file_path)` function but this doesn't seem to exist.
This PR adds it.
> implement the fs::read_to_string function

- src/context.rs
- src/workload.rs
Useful when need to utilize the 'USING TIMESTAMP' Cql feature.
Can be utilized like the following in a rune script:
```
latte::now_timestamp()
```
> Add 'now_timestamp' latte function to be used in rune scripts

- src/context.rs
Update the latte's `to_scylla_value` function (which is used by the `execute_prepared` one) to support `CQL UserDefinedType`s.
If we create UDT like following:
```
let KEYSPACE = "fooks"
let UDT_NAME = "fooudt"
context.execute(`CREATE TYPE IF NOT EXISTS ${KEYSPACE}.${UDT_NAME} (
id bigint, textk1 text, textk2 text)`).await?;
```
And then use it in some table.
Then, with this change, we can use the `rune::runtime::Object` object defined like following:
```
let udtexample = #{
"_keyspace": KEYSPACE, "_type_name": UDT_NAME,
"id": fooid, "textk1": textv1, "textk2": textv2
};
```
in an `execute_prepared` function.
Note that `_keyspace` and `_type_name` are special and required fields which are used to satisfy the Scylla Rust driver's `CqlValue::UserDefinedType` object structure:
```
pub enum …
```
> Add UDT support for prepared statements

- src/context.rs
- src/workload.rs
Usage is as following:
```
pub async fn load(ctxt, i) {
...
let randomstring = latte::text(i, 64);
...
```
> Add `text` latte function for getting random strings in rune scripts

- src/config.rs
- src/context.rs
- src/main.rs
- src/report.rs
- src/stats.rs
With this change it is now possible to configure retry approach for queries.
Following new options are available:
--retry-number=10
--retry-interval=200ms | --retry-interval=100ms,3s
--request-timeout=5
The `--retry-number` option allows to configure number of retries to be applied
in case of query failures. Default is `10`.
The `--retry-interval` option may store one or two time values separated with comma.
Values may have `ms` (milliseconds), `s` (seconds) units.
If 2 are specified then it will be `minimum` and `maximum` waiting interval
with exponential growth based on the made attempts. Default is `100ms,5s`.
The `--request-timeout` allows to configure the time for a query after which
it is considered as 'failed'. Measured in seconds. Default is `5`.
Print only 5 retry error messages …
> Add retry mechanism

- src/config.rs
- src/error.rs
- src/main.rs
Use `latte edit <workload>` to conveniently edit workloads located in non-local workload directory e.g. ones determined by LATTE_WORKLOAD_PATH.
> Add new edit command for editing workloads

- src/report.rs
Before we would have following output on the start of latte:
```
-P str_param
-P int_param        5
```
If we provided following params to the latte command:
```
latte ... -P str_param="\"foo_str\"" -P int_param=5
```
With this change we will have following output:
```
-P str_param        "foo_str"
-P int_param        5
```
> Support printing string values of optional params set with `-P` flag

- src/context.rs
Additionally, some cleanup of error handling has been performed, now all query parameter conversion errors are captured by CassErrorKind::QueryParamConversion.
Some unwraps in code for converting maps have been changed to proper error handling with "?".
> Serialize Rune objects as Cassandra maps

- src/config.rs
- src/context.rs
- src/report.rs
Adding non-optional datacenter field to the config made it impossible to load old reports.
> Use Option for datacenter to keep backwards compatibility

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/main.rs
- src/report.rs
- src/table.rs
This option is intended for quick comparisons of multiple benchmarks or for finding the right benchmark.
The command accepts basic filtering by workload or tags.
Additionally, the speed of loading reports has been significantly improved.
This feature will be enhanced in the future.
> New command: `latte list` for tabular listing of run results

- src/exec.rs
With fixed rate limit, if there is sudden slowdown and the
database can't keep up, latte should not try to issue
more requests in burst after the slow-down is over.
With this fix it will keep the maximum set rate limit.
> Don't try to catch up after slowdown when using fixed rate

- src/context.rs
The following error may happen having some specific cluster conditions:
```
scylla::transport::load_balancing::default \
Datacenter specified as the preferred one (eu-north-1) does not exist! \
error: Cassandra error: Failed to execute query \
"SELECT cluster_name, release_version FROM system.local" \
with params []: Protocol Error: Empty query plan - driver bug!
```
So, this is not critical, much more valueable to continue a test run with a main stress load.
So, catch error if it happens, print it out as warning and continue with `unknown` value as a cluster name.
> Make latte continue running even if cluster_name failed to be read

- .gitignore
- src/exec/workload.rs
- src/report/mod.rs
- src/stats/histogram.rs
Replaces explicit lifetimes with anonymous in accordance with clippy suggestions. This unifies lifetimes usages through the codebase.
Fixes #117
> Elide unnecessary explicit lifetimes

- src/error.rs
Fixes use of only err_derive::Error.
Removes empty implementation block for LatteError.
> Use only used from err_derive and remove empty impl

- src/scripting/bind.rs
In the PR (https://github.com/pkolaczk/latte/pull/96) with the switch from `rune-0.12` to `rune-0.13`
the `blob` function changed it's return type from `rune::runtime::Bytes` to the `Vec<u8>`.
Such a change required also an update to the input values parser
to expect one more input type match to the `ColumnType::Blob`.
So, add the missing parsing element to make the `blob` function work again as it was before.
It will allow to avoid manual wrapping into the
`rune::runtime::Bytes` type in rune scripts.
> Fix blob function usage

- src/scripting/bind.rs
`Timestamp`, `timeuuid` and `inet` data types are already supported.
So, update approriate `todo` comment with proper list of unsupported data types.
> Update todo comment about supported data types
